#include "hk_logging_lwip.h"

#include "hk_logging.h"
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <freertos/queue.h>
#include <lwip/sockets.h>

static const char *err_strerr[] = {
"EPERM, Not owner",
"ENOENT, No such file or directory",
"ESRCH, No such process",
"EINTR, Interrupted system call",
"EIO, I/O error",
"ENXIO, No such device or address",
"E2BIG, Arg list too long",
"ENOEXEC, Exec format error",
"EBADF, Bad file number",
"ECHILD, No children",
"EAGAIN, No more processes",
"ENOMEM, Not enough space",
"EACCES, Permission denied",
"EFAULT, Bad address",
"ENOTBLK, Block device required",
"EBUSY, Device or resource busy",
"EEXIST, File exists",
"EXDEV, Cross-device link",
"ENODEV, No such device",
"ENOTDIR, Not a directory",
"EISDIR, Is a directory",
"EINVAL, Invalid argument",
"ENFILE, Too many open files in system",
"EMFILE, File descriptor value too large",
"ENOTTY, Not a character device",
"ETXTBSY, Text file busy",
"EFBIG, File too large",
"ENOSPC, No space left on device",
"ESPIPE, Illegal seek",
"EROFS, Read-only file system",
"EMLINK, Too many links",
"EPIPE, Broken pipe",
"EDOM, Mathematics argument out of domain of function",
"ERANGE, Result too large",
"ENOMSG, No message of desired type",
"EIDRM, Identifier removed",
"ECHRNG, Channel number out of range",
"EL2NSYNC, Level 2 not synchronized",
"EL3HLT, Level 3 halted",
"EL3RST, Level 3 reset",
"ELNRNG, Link number out of range",
"EUNATCH, Protocol driver not attached",
"ENOCSI, No CSI structure available",
"EL2HLT, Level 2 halted",
"EDEADLK, Deadlock",
"ENOLCK, No lock",
"Unknown error",
"Unknown error",
"Unknown error",
"EBADE, Invalid exchange",
"EBADR, Invalid request descriptor",
"EXFULL, Exchange full",
"ENOANO, No anode",
"EBADRQC, Invalid request code",
"EBADSLT, Invalid slot",
"EDEADLOCK, File locking deadlock error",
"EBFONT, Bad font file fmt",
"Unknown error",
"Unknown error",
"ENOSTR, Not a stream",
"ENODATA, No data (for no delay io)",
"ETIME, Stream ioctl timeout",
"ENOSR, No stream resources",
"ENONET, Machine is not on the network",
"ENOPKG, Package not installed",
"EREMOTE, The object is remote",
"ENOLINK, Virtual circuit is gone",
"EADV, Advertise error",
"ESRMNT, Srmount error",
"ECOMM, Communication error on send",
"EPROTO, Protocol error",
"Unknown error",
"Unknown error",
"EMULTIHOP, Multihop attempted",
"ELBIN, Inode is remote (not really error)",
"EDOTDOT, Cross mount point (not really error)",
"EBADMSG, Bad message",
"Unknown error",
"EFTYPE, Inappropriate file type or format",
"ENOTUNIQ, Given log. name not unique",
"EBADFD, f.d. invalid for this operation",
"EREMCHG, Remote address changed",
"ELIBACC, Can't access a needed shared lib",
"ELIBBAD, Accessing a corrupted shared lib",
"ELIBSCN, .lib section in a.out corrupted",
"ELIBMAX, Attempting to link in too many libs",
"ELIBEXEC, Attempting to exec a shared library",
"ENOSYS, Function not implemented",
"ENMFILE, No more files",
"ENOTEMPTY, Directory not empty",
"ENAMETOOLONG, File or path name too long",
"ELOOP, Too many symbolic links",
"Unknown error",
"Unknown error",
"EOPNOTSUPP, Operation not supported on socket",
"EPFNOSUPPORT, Protocol family not supported",
"Unknown error",
"Unknown error",
"Unknown error",
"Unknown error",
"Unknown error",
"Unknown error",
"Unknown error",
"ECONNRESET, Connection reset by peer",
"ENOBUFS, No buffer space available",
"EAFNOSUPPORT, Address family not supported by protocol family",
"EPROTOTYPE, Protocol wrong type for socket",
"ENOTSOCK, Socket operation on non-socket",
"ENOPROTOOPT, Protocol not available",
"ESHUTDOWN, Can't send after socket shutdown",
"ECONNREFUSED, Connection refused",
"EADDRINUSE, Address already in use",
"ECONNABORTED, Software caused connection abort",
"ENETUNREACH, Network is unreachable",
"ENETDOWN, Network interface is not configured",
"ETIMEDOUT, Connection timed out",
"EHOSTDOWN, Host is down",
"EHOSTUNREACH, Host is unreachable",
"EINPROGRESS, Connection already in progress",
"EALREADY, Socket already connected",
"EDESTADDRREQ, Destination address required",
"EMSGSIZE, Message too long",
"EPROTONOSUPPORT, Unknown protocol",
"ESOCKTNOSUPPORT, Socket type not supported",
"EADDRNOTAVAIL, Address not available",
"ENETRESET, Connection aborted by network",
"EISCONN, Socket is already connected",
"ENOTCONN, Socket is not connected",
"ETOOMANYREFS",
"EPROCLIM",
"EUSERS",
"EDQUOT",
"ESTALE",
"ENOTSUP, Not supported",
"ENOMEDIUM, No medium (in tape drive)",
"ENOSHARE, No such host or network path",
"ECASECLASH, Filename exists with different case",
"EILSEQ, Illegal byte sequence",
"EOVERFLOW, Value too large for defined data type",
"ECANCELED, Operation canceled",
"ENOTRECOVERABLE, State not recoverable",
"EOWNERDEAD, Previous owner died",
"ESTRPIPE, Streams pipe error",
};

void hk_log_lwip_err(int session, const char * message)
{
    int err = errno - 1;
    const char *err_str;
    if (err < 0 || err > 143)
    {
        err_str ="Unknown error.";
    }
    else
    {
        err_str = err_strerr[err];
    }

    HK_LOGW("%d - %s. Error code: %d, Error message: %s", session, message, err + 1, err_str);
}