/**
 * @file hk_srvs.h
 *
 * Holdes the services of homekit.
 */

#pragma once

typedef enum {
    HK_SRV_ACCESSORY_INFORMATION = 0x3E,
    HK_SRV_FAN = 0x40,
    HK_SRV_GARAGE_DOOR_OPENER = 0x41,
    HK_SRV_LIGHTBULB = 0x43,
    HK_SRV_LOCK_MANAGEMENT = 0x44,
    HK_SRV_LOCK_MECHANISM = 0x45,
    HK_SRV_OUTLET = 0x47,
    HK_SRV_SWITCH = 0x49,
    HK_SRV_PARIRING = 0x55,
    HK_SRV_THERMOSTAT = 0x4A,
    HK_SRV_AIR_QUALITY_SENSOR = 0x8D,
    HK_SRV_SECURITY_SYSTEM = 0x7E,
    HK_SRV_CARBON_MONOXIDE_SENSOR = 0x7F,
    HK_SRV_CONTACT_SENSOR = 0x80,
    HK_SRV_DOOR = 0x81,
    HK_SRV_HUMIDITY_SENSOR = 0x82,
    HK_SRV_LEAK_SENSOR = 0x83,
    HK_SRV_LIGHT_SENSOR = 0x84,
    HK_SRV_MOTION_SENSOR = 0x85,
    HK_SRV_OCCUPANCY_SENSOR = 0x86,
    HK_SRV_SMOKE_SENSOR = 0x87,
    HK_SRV_STATELESS_PROGRAMMABLE_SWITCH= 0x89,
    HK_SRV_TEMPERATURE_SENSOR = 0x8A,
    HK_SRV_WINDOW = 0x8B,
    HK_SRV_WINDOW_COVERING = 0x8C,
    HK_SRV_BATTERY_SERVICE = 0x96,
    HK_SRV_CARBON_DIOXIDE_SENSOR = 0x97,
    HK_SRV_CAMERA_RTP_STREAM_MANAGEMENT = 0x110,
    HK_SRV_MICROPHONE = 0x112,
    HK_SRV_SPEAKER = 0x113,
    HK_SRV_DOORBELL = 0x121,
    HK_SRV_HAP_PROTOCOL_INFORMATION = 0xA2,
    HK_SRV_FAN_V2 = 0xB7,
    HK_SRV_SLAT = 0xB9,
    HK_SRV_FILTER_MAINTENANCE = 0xBA,
    HK_SRV_AIR_PURIFIER = 0xBB,
    HK_SRV_SERVICE_LABEL = 0xCC,
} hk_srv_types_t;